import type { Metadata } from "next";
import { Montserrat, Lacquer } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";

// Load Montserrat
const montserrat = Montserrat({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

// Load Lacquer
const lacquer = Lacquer({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-lacquer',
});

// Load Faculty Glyphic locally
const facultyGlyphic = localFont({
  src: './fonts/FacultyGlyphic.ttf',
  variable: '--font-faculty',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${lacquer.variable} ${facultyGlyphic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}